### ISSUE TITLE
Post-install run build/start is failing 

### ISSUE THREAD

**Issue by satyabharadwaja** [PDFTron/webviewer-ui#1042]
node -v v20.11.0
node-gyp -v v10.0.1
Webviewer 10.6
OpenSSL 3.1.4 24 Oct 2023 (Library: OpenSSL 3.1.4 24 Oct 2023)

While running the commands: npm start, npm run build, it keeps failing
Was following instructions as per : https://docs.apryse.com/documentation/web/guides/advanced-customization/
Even npm run download-webviewer was failing ..But after multiple iterations ,somehow it got resolved.
(Having issues with other node versions. So was not switching to them)

$ npm run build

> webviewer-ui@10.6.0 build
> npm run clean && npm run bundle

> webviewer-ui@10.6.0 clean
> rimraf build

> webviewer-ui@10.6.0 bundle
> webpack --progress --config ./webpack.config.prod.js

<s> [webpack.Progress] 0% compiling
<s> [webpack.Progress] 10% building 0/0 modules 0 active
<s> [webpack.Progress] 10% building 0/1 modules 1 active C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\babel-loader\lib\index.js??ref--4!C:\WebViewer_Feb3_Node20\webviewer-ui\src\index.js
node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\babel-loader\lib\index.js:44:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.11.0

$ npm start

> webviewer-ui@10.6.0 start
> npx babel-node ./dev-server.js

Listening at localhost:3000 (http://192.168.0.105:3000)
node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\WebViewer_Feb3_Node20\webviewer-ui\node_modules\loader-runner\lib\LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.11.0

**Comment by bollain** [comment]
Hi @satyabharadwaja,

At this time this repo requires Node v16 and NPM v8.

We also do not recommend you use the `download-webviewer` as it has a dependency that sometimes fails - the preferred way to install the core dependencies is via the NPM package. 
https://github.com/PDFTron/webviewer-ui?tab=readme-ov-file#install-webviewer-core-dependencies
